name: Build and upload book
on:
  push:
    branches:
      - master

jobs:
  bookdown:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker build
        run: |
          cd the-1-hour-event-storming-book
          ./_build_with_docker.sh
      - name: upload book
        uses: actions/upload-artifact@v3
        with:
          name: the-1-hour-event-storming-book
          path: the-1-hour-event-storming-book/The-1-hour-Event-Storming-book.epub

# Refs:
# - https://lalejini.com/2021/01/09/bookdown-autodeploy.html
# - https://github.com/actions/upload-artifact