name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}